name: Python install with pipx

on:
  schedule:
  - cron: 0 2 * * *
  push:

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pipx
        python -m pipx ensurepath

    - name: Install with pipx (Linux)
      if: runner.os == 'Linux'
      run: |
        source ~/.profile
        pipx install --verbose --python python3.7 yawast
      shell: bash {0}

    - name: Install with pipx (Windows)
      if: runner.os == 'Windows'
      run: |
        set PATH=%USERPROFILE%\.local\bin;%PATH%
        echo %PATH%
        pipx install --verbose yawast
      shell: cmd

    - name: Install with pipx (macOS)
      if: runner.os == 'macOS'
      run: |
        export PATH=$PATH:/Users/runner/.local/bin
        pipx install --verbose --python python3.7 yawast
      shell: bash {0}

    - name: Run version (Linux)
      if: runner.os == 'Linux'
      run: |
        source ~/.profile
        yawast version
      shell: bash {0}

    - name: Run version (Windows)
      if: runner.os == 'Windows'
      run: |
        %USERPROFILE%\.local\bin\yawast version
      shell: cmd

    - name: Run version (macOS)
      if: runner.os == 'macOS'
      run: |
        export PATH=$PATH:/Users/runner/.local/bin
        yawast version
      shell: bash {0}
